---
- name: Copy default Jitsi meet config file.
  command: >
    cp /etc/jitsi/meet/localhost-config.js
       /etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js
  args:
    creates: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
  notify: restart jitsi-videobridge

- name: Set the Jitsi Meet hostname
  replace:
    dest: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
    regexp: "^(.*)localhost(.*)"
    replace: "\\1{{ jitsi_meet_server_name }}\\2"
  notify: restart jitsi-videobridge

- name: Disable third party resources in Jitsi Meet config.
  lineinfile:
    dest: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
    regexp: "^    disableThirdPartyRequests"
    line: "    disableThirdPartyRequests: true,"
    state: present
  notify: restart jitsi-videobridge

- name: Set hostname in Jicofo config.
  lineinfile:
    dest: /etc/jitsi/jicofo/config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^JICOFO_HOST='
      line: "JICOFO_HOST=localhost"
    - regexp: '^JICOFO_HOSTNAME='
      line: "JICOFO_HOSTNAME={{ jitsi_meet_server_name }}"
    - regexp: '^JICOFO_AUTH_DOMAIN='
      line: "JICOFO_AUTH_DOMAIN=auth.{{ jitsi_meet_server_name }}"
    - regexp: '^JICOFO_SECRET='
      line: "JICOFO_SECRET={{ jitsi_meet_jicofo_secret }}"
    - regexp: '^JICOFO_AUTH_PASSWORD='
      line: "JICOFO_AUTH_PASSWORD={{ jitsi_meet_jicofo_password }}"
  notify: restart jicofo

- name: Set hostname in Videobridge config.
  lineinfile:
    dest: /etc/jitsi/videobridge/config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^JVB_HOST='
      line: "JVB_HOST="
    - regexp: '^JVB_HOSTNAME='
      line: "JVB_HOSTNAME={{ jitsi_meet_server_name }}"
    - regexp: '^JVB_SECRET='
      line: "JVB_SECRET={{ jitsi_meet_videobridge_secret }}"
  notify: restart jitsi-videobridge

- name: Remove default localhost Jitsi Meet config file.
  file:
    path: /etc/jitsi/meet/localhost-config.js
    state: absent
  notify: restart jitsi-videobridge

- name: Set debconf options for jitsi-meet.
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - name: jitsi-meet
      question: jitsi-meet/jvb-hostname
      value: "{{ jitsi_meet_server_name }}"
      vtype: string
    - name: jitsi-meet
      question: jitsi-meet/jvb-serve
      value: "false"
      vtype: boolean
    - name: jitsi-meet-prosody
      question: jitsi-meet-prosody/jvb-hostname
      value: "{{ jitsi_meet_server_name }}"
      vtype: string
  notify:
    - restart jitsi-videobridge
    - restart jicofo
    - restart prosody
