---
# tasks file for jitsi-meet
- name: Install some dependencies for Jitsi Meet
  apt:                                                                          
    name: "{{ item }}"                                                          
    state: present    
  with_items:                                      
    - git
    - build-essential

- name: Install some dependencies for Jitsi Meet                                
  apt:                                                                          
    name: "{{ item }}"                                                          
    state: present
    update_cache: yes                                                              
  with_items:                                                                   
    - nodejs-legacy
    - npm

- name: Clone git repository for Jitsi Meet
  git:                                                                          
    repo: https://github.com/jitsi/jitsi-meet
    dest: /var/www/jitsi
    version: master
    force: yes                                            
    depth: 1
 
- name: Install Node.js dependencies
  command: npm install --production
  args:                                      
    chdir: /var/www/jitsi

- name: Disable third party resources
  lineinfile:
    dest: /var/www/jitsi/config.js
    regexp: "^    disableThirdPartyRequests"
    line: "   disableThirdPartyRequests: true"
    state: present

- name: Build the Jitsi Meet application                                        
  command: make                                                                 
  args:                                                                         
    chdir: /var/www/jitsi
  ignore_errors: yes
