---
- name: Install Jitsi apt repo
  copy:
    src: jitsi.list
    dest: /etc/apt/sources.list.d/jitsi.list

- name: Add signing key for Jitsi repository
  apt_key:
    keyserver: keys.gnupg.net
    id: C697D823EB0AB654

- name: Install Java JRE
  apt:
    name: default-jre-headless
    state: present

- name: Disable MEMPROTECT on Java
  command: paxctl -cm /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  ignore_errors: yes

- name: Install Jitsi Meet
  apt:
    name: jitsi-meet
    state: present
    update_cache: yes

- name: Disable third party resources
  lineinfile:
    dest: /etc/jitsi/meet/localhost-config.js
    regexp: "^    disableThirdPartyRequests"
    line: "    disableThirdPartyRequests: true,"
    state: present

- name: Set the Jitsi Meet hostname
  lineinfile:
    dest: /etc/jitsi/meet/localhost-config.js
    regexp: "^        domain: "
    line: "        domain: '{{ jitsi_meet_hostname }}',"
    state: present

- name: Update the SSL cert and key
  lineinfile:
    dest: /etc/nginx/sites-enabled/localhost.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^    ssl_certificate "
      line: "    ssl_certificate {{ ssl_cert_path }};"
    - regexp: "^    ssl_certificate_key "
      line: "    ssl_certificate_key {{ ssl_key_path }};"
  notify: restart nginx

- name: Deactivate the default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

# the following task depends upon the fpf-hardening role
- name: Configure automatic upgrades for Jitsi Meet
  lineinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: "^        \"o=Debian,n=jessie,l=Debian-Security\";"
    line: "        \"o=jitsi.org,l=Jitsi Debian packages repository\";"
    state: present

- name: Install ufw package.
  apt:
    name: ufw
    state: present

- name: Specify allowed ports in firewall config.
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 80
    - 443
    - 4443
  notify: reload ufw

- name: Open UDP port 10000 for jitsi-videobridge
  ufw:
    rule: allow
    port: 10000
    proto: udp
  notify: reload ufw

- name: Ensure UFW is running.
  ufw:
    name: ufw
    state: enabled
