---
- include: packages.yml

  # Read Jitsi Meet config files and extract secrets for use in template configs.
  # Import to run these tasks after package installation, but before config tasks.
- include: dynamic_vars.yml

- include: prosody.yml

- include: jitsi_meet.yml

- include: jicofo.yml

- include: nginx.yml

- include: clean_up_default_configs.yml
  when: jitsi_meet_ssl_cert_path != '' and
        jitsi_meet_ssl_key_path != ''

- include: ufw.yml
  when: jitsi_meet_configure_firewall == true

  # Placing the browser extensions last so the associated debugging tasks
  # that display URLs are visible near the end of the play.
- include: browser_extensions.yml
